### ISSUE TITLE
cd Hacke-WiFi

### ISSUE THREAD

**Issue by EthicalMD55** [TheTeamAlexa/Hacke-WiFi#1]
bash: cd: Hacke-WiFi: No such file or directory

Please solve the problem

**Comment by Petros626** [comment]
The fault is up to you not the shell script.. Think about it

**Comment by TheTeamAlexa** [comment]
> bash: cd: Hacke-WiFi: No such file or directory
> 
> Please solve the problem

You have to first clone `git clone https://github.com/TheTeamAlexa/Hacke-WiFi` this then access this repository by `cd  Hacke-WiFi`
